[package]
name = "file-rotate"
version = "0.2.0"
authors = ["Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"
description = "Log rotation for files"
homepage = "https://github.com/BourgondAries/file-rotate"
repository = "https://github.com/BourgondAries/file-rotate"
keywords= ["log", "rotate", "logrotate"]
license = "LGPL-3.0-or-later"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
